version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo Instalar las dependencias de Python pull
      - pip3 install --upgrade pip
      - pip3 install pytest
      - pip3 install -r backend/requirements.txt
      - rm -rf dspt
      - mkdir backend/test-reports
  build:
    commands:
      - echo Ejecutar comando de pruebas pytest
      - cd backend
      - python -m pytest
        -s
        -v
        --junitxml=test-reports/junit.xml 
        --log-file=test-reports/logs.txt
reports:
  report:
    files:
      - 'junit.xml'
    base-directory: 'backend/test-reports'
    discard-paths: yes
    file-format: JunitXml