version: 0.2

phases:
  install:
     commands:
        - yum install -y yum-utils
        - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
        - yum -y install terraform
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - cd talleres/02/terraform
      - terraform init
  build:
    commands:
      - echo Build started on 'date'
  post_build:
    commands:
      - echo Build completed on `date`